[package]
name = "jwt-decode"
version = "0.1.0"
authors = ["Brad Osgood <bosgood@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "6"
serde_derive = "1"
serde = "1"
