[package]
name = "jwt-decode"
version = "0.1.0"
authors = ["Brad Osgood <bosgood@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
serde_json = "1.0"